### ISSUE TITLE
SyntaxError using Python 3.5.3

### ISSUE THREAD

**Issue by suranap** [rocky/python-uncompyle6#127]
i'm using a package called `hypothesis`, which depends on `uncompyle6`. The update today broke my build. Here's a clean environment where I installed `uncompyle6`: 

```
$ pip list
Package      Version
------------ -------
click        6.7    
pip          9.0.1  
py           1.4.34 
setuptools   28.8.0 
spark-parser 1.6.1  
uncompyle6   2.11.4 
xdis         3.5.4  
(test_pytest) [surana@scooby testpytest]$ uncompyle6 -h
Traceback (most recent call last):
  File "/Users/surana/.pyenv/versions/test_pytest/bin/uncompyle6", line 11, in <module>
    load_entry_point('uncompyle6==2.11.4', 'console_scripts', 'uncompyle6')()
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/uncompyle6/__init__.py", line 48, in <module>
    import uncompyle6.semantics.pysource
  File "/Users/surana/.pyenv/versions/3.5.3/envs/test_pytest/lib/python3.5/site-packages/uncompyle6/semantics/pysource.py", line 2091
    except python_parser.ParserError, e:
                                    ^
SyntaxError: invalid syntax
(test_pytest) [surana@scooby testpytest]$ python --version
Python 3.5.3
```

**Comment by suranap** [comment]
Never mind. `hypothesis` dropped this lib a while ago. I was pinned on an older version of `hypothesis`, but its dependencies are not pinned.

**Comment by rocky** [comment]
Ah, ok. But this is still bad. Investigating, it looks like you were getting the code from the Python-2.4 branch instead of the master branch. And that seems to be because I have the 2.4 branch in the tarball. I've just removed the tarball leaving eggs. 

I usually have a wheel, but I need to figure out how to limit that to specific versions, in particular just Python 2.6 on, or 2.6, 2.7 and all of Python 3.
