### ISSUE TITLE
ImportError: Unknown magic number 62161 

### ISSUE THREAD

**Issue by gaoruojie** [rocky/python-uncompyle6#142]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/uncompyle6", line 11, in <module>
    sys.exit(main_bin())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/uncompyle6/bin/uncompile.py", line 163, in main_bin
    **options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/uncompyle6/main.py", line 146, in main
    decompile_file(infile, outstream, showasm, showast, showgrammar)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/uncompyle6/main.py", line 63, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xdis/load.py", line 95, in load_module
    fast_load=fast_load, get_code=get_code)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xdis/load.py", line 124, in load_module_from_file_object
    (ord(magic[0])+256*ord(magic[1]), filename))
ImportError: Unknown magic number 62161 in routers2.pyc

**Comment by rocky** [comment]
That magic number has been in xdis for over a year. So what version of xdis are you running? 

Please reread the what-to-send minimum requirements section of [HOW-TO-REPORT-A-BUG.md](https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#what-to-send-minimum-requirements).

**Comment by gaoruojie** [comment]
rocky, thank you very much for your reply, the .pyc file can be downloaded from here:
https://drive.google.com/file/d/1PLMGyio8EiI48CVTyg0apY-WIXKl2oRt/view?usp=sharing
for xdis version
I tried 
pip install xdis
and this is what I got
Requirement already satisfied: xdis in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xdis-3.6.2-py2.7.egg 
so, I think it's up to date?

**Comment by rocky** [comment]
router2.pyc is not valid python bytecode.  Read the section in HOW TO REPORT A BUG on "Do I have valid python." and come back after you have read HOW TO REPORT A BUG.

**Comment by gaoruojie** [comment]
Luckily, I did read the HOW TO REPORT A BUG document carefully, and found that the crazy-compilers.com offers a great decompile service at a reasonable price. I uploaded the python bytecode and they emailed me the source code according.
Again, thank you very much for your replies, they did helped me to solve my problem.

**Comment by rocky** [comment]
I am very glad to hear that crazy-compilers.com was able to help you out and that they have great service.  Tell your friends - they deserve more business.
