### ISSUE TITLE
ImportError: Unknown magic number 227 in file.pyc

### ISSUE THREAD

**Issue by sieunhando** [rocky/python-uncompyle6#164]
Hi, I have a problem when I run "uncompyle6 MegarangerCLI.pyc"
```
Traceback (most recent call last):
  File "/usr/bin/uncompyle6", line 11, in <module>
    load_entry_point('uncompyle6', 'console_scripts', 'uncompyle6')()
  File "/home/beo/Downloads/python-uncompyle6-release-python-2.4-3.1.0/uncompyle6/bin/uncompile.py", line 172, in main_bin
    **options)
  File "/home/beo/Downloads/python-uncompyle6-release-python-2.4-3.1.0/uncompyle6/main.py", line 226, in main
    linemap_stream, do_fragments)
  File "/home/beo/Downloads/python-uncompyle6-release-python-2.4-3.1.0/uncompyle6/main.py", line 137, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "/usr/lib/python2.7/site-packages/xdis/load.py", line 108, in load_module
    fast_load=fast_load, get_code=get_code)
  File "/usr/lib/python2.7/site-packages/xdis/load.py", line 139, in load_module_from_file_object
    (ord(magic[0])+256*ord(magic[1]), filename))
ImportError: Unknown magic number 227 in xxx.pyc
```
Please tell me how to fix it. Thanks

**Comment by rocky** [comment]
Do you have valid bytecode?

Read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#do-you-have-valid-bytecode

If you have valid bytecode you should be able to disassemble it.

**Comment by sieunhando** [comment]
And also this too.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xdis/load.py", line 106, in load_module
    version = float(magics.versions[magic][:3])
KeyError: b'\xe3\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./uncompyle6", line 3, in <module>
    main_bin()
  File "/usr/lib/python3.6/site-packages/uncompyle6/bin/uncompile.py", line 163, in main_bin
    **options)
  File "/usr/lib/python3.6/site-packages/uncompyle6/main.py", line 146, in main
    decompile_file(infile, outstream, showasm, showast, showgrammar)
  File "/usr/lib/python3.6/site-packages/uncompyle6/main.py", line 63, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "/usr/lib/python3.6/site-packages/xdis/load.py", line 110, in load_module
    (ord(magic[0])+256*ord(magic[1]), filename))
TypeError: ord() expected string of length 1, but int found

```
