### ISSUE TITLE
Error with when trying to decompyle KeyError:'2.7.15candidate1'

### ISSUE THREAD

**Issue by kdeltared** [rocky/python-uncompyle6#176]
Hi, Im getting this error when tryinh to decompile a pyo file. I suppose that's because the version is too new, but I don't know. 

Please, see the Traceback below

```
Traceback (most recent call last):
  File "/usr/local/bin/uncompyle6", line 7, in <module>
    from uncompyle6.bin.uncompile import main_bin
  File "/usr/local/lib/python2.7/dist-packages/uncompyle6/__init__.py", line 48, in <module>
    import uncompyle6.semantics.pysource
  File "/usr/local/lib/python2.7/dist-packages/uncompyle6/semantics/pysource.py", line 133, in <module>
    from uncompyle6.parsers.astnode import AST
  File "/usr/local/lib/python2.7/dist-packages/uncompyle6/parsers/astnode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "/usr/local/lib/python2.7/dist-packages/uncompyle6/scanners/tok.py", line 122, in <module>
    NoneToken = Token('LOAD_CONST', offset=-1, attr=None, pattr=None)
  File "/usr/local/lib/python2.7/dist-packages/uncompyle6/scanners/tok.py", line 48, in __init__
    from xdis.std import _std_api
  File "/usr/local/lib/python2.7/dist-packages/xdis/std.py", line 211, in <module>
    _std_api = make_std_api()
  File "/usr/local/lib/python2.7/dist-packages/xdis/std.py", line 208, in make_std_api
    return _StdApi(python_version, variant)
  File "/usr/local/lib/python2.7/dist-packages/xdis/std.py", line 72, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/usr/local/lib/python2.7/dist-packages/xdis/op_imports.py", line 125, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '2.7.15candidate1'
```
Thank you!

**Comment by rocky** [comment]
Recently when I installed ubuntu bionic, I noticed that this ships with 2.7.5rc1. 

So with release 3.2.0 (c2181e3235e37ceda682d6b80ce6a3b6fe41dc6a) using xdis 3.8.2, this is fixed.
