### ISSUE TITLE
Error when running uncompyle6

### ISSUE THREAD

**Issue by Cookieheld** [rocky/python-uncompyle6#194]
That's what im getting

`C:\WINDOWS\system32>uncompyle6
Traceback (most recent call last):
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User-PC\AppData\Local\Programs\Python\Python37-32\Scripts\uncompyle6.exe\__main__.py", line 5, in <module>
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\uncompyle6\__init__.py", line 48, in <module>
    import uncompyle6.semantics.pysource
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\uncompyle6\semantics\pysource.py", line 133, in <module>
    from uncompyle6.parsers.astnode import AST
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\uncompyle6\parsers\astnode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\uncompyle6\scanners\tok.py", line 122, in <module>
    NoneToken = Token('LOAD_CONST', offset=-1, attr=None, pattr=None)
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\uncompyle6\scanners\tok.py", line 48, in __init__
    from xdis.std import _std_api
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\xdis\std.py", line 211, in <module>
    _std_api = make_std_api()
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\xdis\std.py", line 208, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\xdis\std.py", line 72, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\users\user-pc\appdata\local\programs\python\python37-32\lib\site-packages\xdis\op_imports.py", line 133, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.7.1'`

**Comment by rocky** [comment]
So you are using the recently released Python 3.7.1 are you? Ok. I've updated on Pypi the dependent xdis  (cross platform disassembler) package. Pull that down and Python 3.7.1 will be recognized. 

But be warned: Python 3.7.x decompilation is pretty weak especially yet again in control flow. I'm not planning on doing anything about this, unitl a after a major refactor for how is done to detect control flow. 

Also, when reporting a bug, read and follow the guidelines.
