### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by deajan** [rocky/python-uncompyle6#197]
Hello,

I'm trying to learn a bit Python, and packaged one of my programs with PyInstaller, now checking how hard it would be to get the original source code, and what would it look like.
Using Python 3.7.1, used PyInstaller archive_viewer.py to extract the main bytecode file from the standalone executable, and installed Uncompyle6 3.2.4 to get back to the source.
I got the following error:

```
uncompyle6 imf_thread.pyc
Traceback (most recent call last):
  File "c:\python37-32\lib\site-packages\xdis\load.py", line 131, in load_module_from_file_object
    float_version = float(magics.versions[magic][:3])
KeyError: b'\xe3\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37-32\Scripts\uncompyle6.exe\__main__.py", line 9, in <module>
  File "c:\python37-32\lib\site-packages\uncompyle6\bin\uncompile.py", line 181, in main_bin
    **options)
  File "c:\python37-32\lib\site-packages\uncompyle6\main.py", line 230, in main
    linemap_stream, do_fragments)
  File "c:\python37-32\lib\site-packages\uncompyle6\main.py", line 133, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "c:\python37-32\lib\site-packages\xdis\load.py", line 107, in load_module
    fast_load=fast_load, get_code=get_code)
  File "c:\python37-32\lib\site-packages\xdis\load.py", line 136, in load_module_from_file_object
    (ord(magic[0])+256*ord(magic[1]), filename))
TypeError: ord() expected string of length 1, but int found
```

Willing to share my bytecode as well as source code, just need to anonymize the original source first if needed.
Running on Windows 10 x64 with Python 3.7.1 x86.

Compiling the source itself with python -m compileall and using uncompyle6 afterwards works more or less, I get most of the source and a couple of ```Parse error at or near `FOR_ITER' instruction at offset 134``` errors.
So I guess there's something with the PyInstaller bytecode that uncompyle6 cannot deal with, yet ?

Anyway, got the answer I was asking myself, and yes: the code is totally readable, even variable names are kept, didn't think it would be that readable :)

**Comment by rocky** [comment]
I'm glad you figured out your problem. 

As for `Parse error at or near `FOR_ITER' instruction at offset 134` if you want that particular problem addressed, narrow down the source code the smallest program that exhibits the problem. 

 (but it is well known that there are a number of problems decompiling 3.7.1 and eventually they will get addressed. Also (re)read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md
