### ISSUE TITLE
python 3.7.2 ValueError: bad marshal data 

### ISSUE THREAD

**Issue by tomopon69** [rocky/python-uncompyle6#216]
I get the following error, but is the program created in python 3.7.2 not decompiled?
Please reply.

usage environment
py3.7.2 uncompyle6 v3.2.5 win10&mac

>Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xdis-3.8.9-py3.7.egg/xdis/load.py", line 189, in load_module_from_file_object
    co = marshal.loads(bytecode)
ValueError: bad marshal data (unknown type code)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xdis-3.8.9-py3.7.egg/xdis/load.py", line 189, in load_module_from_file_object
ValueError: bad marshal data (unknown type code)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/uncompyle6", line 10, in <module>
    sys.exit(main_bin())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uncompyle6/bin/uncompile.py", line 181, in main_bin
    **options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uncompyle6/main.py", line 232, in main
    linemap_stream, do_fragments)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/uncompyle6/main.py", line 133, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xdis-3.8.9-py3.7.egg/xdis/load.py", line 107, in load_module
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xdis-3.8.9-py3.7.egg/xdis/load.py", line 202, in load_module_from_file_object
ImportError: Ill-formed bytecode file test.pyc
<class 'ValueError'>; bad marshal data (unknown type code)

**Comment by rocky** [comment]
> Please reply.

Ok. Please read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md#is-it-really-a-bug and follow the guidelines given in the template when you create an issue.
