### ISSUE TITLE
Trying to decompile 3.7.4 code I get: KeyError: '3.7.4'

### ISSUE THREAD

**Issue by hlyl** [rocky/python-uncompyle6#280]
## Description
When trying to decompile a PYC file version 3.7.4 i get the following error message.
Any tip on how to proceed....

`Traceback (most recent call last):
  File "C:\Python37\Scripts\uncompyle6-script.py", line 11, in <module>
    load_entry_point('uncompyle6==3.3.5', 'console_scripts', 'uncompyle6')()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\python37\lib\site-packages\uncompyle6-3.3.5-py3.7.egg\uncompyle6\__init__.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\python37\lib\site-packages\uncompyle6-3.3.5-py3.7.egg\uncompyle6\semantics\pysource.py", line 136, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\python37\lib\site-packages\uncompyle6-3.3.5-py3.7.egg\uncompyle6\parsers\treenode.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\python37\lib\site-packages\uncompyle6-3.3.5-py3.7.egg\uncompyle6\scanners\tok.py", line 163, in <module>
  File "c:\python37\lib\site-packages\uncompyle6-3.3.5-py3.7.egg\uncompyle6\scanners\tok.py", line 59, in __init__
  File "c:\python37\lib\site-packages\xdis-4.0.2-py3.7.egg\xdis\std.py", line 214, in <module>
    _std_api = make_std_api()
  File "c:\python37\lib\site-packages\xdis-4.0.2-py3.7.egg\xdis\std.py", line 212, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\python37\lib\site-packages\xdis-4.0.2-py3.7.egg\xdis\std.py", line 72, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\python37\lib\site-packages\xdis-4.0.2-py3.7.egg\xdis\op_imports.py", line 143, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.7.4'`

## Environment

Name: uncompyle6
Version: 2.11.5
Summary: Python cross-version byte-code deparser
Home-page: https://github.com/rocky/python-uncompyle6/
Author: Rocky Bernstein, Hartmut Goebel, John Aycock, and others
Author-email: rb@dustyfeet.com
License: MIT
Location: c:\users\hlyng\appdata\roaming\python\python37\site-packages
Requires: spark-parser, xdis, six
`
- OS and Version: Windows 10

**Comment by rocky** [comment]
The latest Python versions including 3.7.4, 3.6.9, and 3.8.0beta2 have been added to the xdis github repository https://github.com/rocky/python-xdis/releases

A new release of xdis will probably go out within a week or so. Until then you can use what's in the github repository.

**Comment by hlyl** [comment]
Any guide or instruction on how to combine the xdis github with uncompyle6 ?

**Comment by rocky** [comment]
xdis 4.0.3 is out. Use that.
