### ISSUE TITLE
TypeError: intern() argument 1 must be str, not list (decompiled from Python 3.7.4)

### ISSUE THREAD

**Issue by laike9m** [rocky/python-uncompyle6#281]
Steps to reproduce:

1. Install Python 3.7.4 and `pip install uncompyle6`

2. Create `uncompile.py` with the following content
```
def main():
    pass

if __name__ == "__main__":
    main()
```

3. Run
```
python -m compileall uncompile.py
uncompyle6 __pycache__/uncompile.cpython-37.pyc
```

Full error log
```
# uncompyle6 version 3.3.5
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.7.4 (default, Jul 28 2019, 01:26:02)
# [Clang 10.0.1 (clang-1001.0.46.4)]
# Embedded file name: uncompile.py
# Size of source mod 2**32: 61 bytes
Traceback (most recent call last):
  File "/Users/laike9m/.pyenv/versions/3.7.4/bin/uncompyle6", line 10, in <module>
    sys.exit(main_bin())
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/bin/uncompile.py", line 183, in main_bin
    **options)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/main.py", line 250, in main
    source_encoding, linemap_stream, do_fragments)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/main.py", line 165, in decompile_file
    mapstream=mapstream, do_fragments=do_fragments)]
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/main.py", line 117, in decompile
    is_pypy=is_pypy)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 2400, in code_deparse
    deparsed.gen_source(deparsed.ast, co.co_name, customize)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 2244, in gen_source
    self.text = self.traverse(ast, is_lambda=is_lambda)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 356, in traverse
    self.preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 107, in preorder
    self.default(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 2016, in default
    self.template_engine(table[key.kind], node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 1930, in template_engine
    self.preorder(node[index])
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 112, in preorder
    self.preorder(kid)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 107, in preorder
    self.default(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 2016, in default
    self.template_engine(table[key.kind], node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 1947, in template_engine
    self.preorder(node[index])
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 105, in preorder
    func(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 519, in n_expr
    self.preorder(node[0])
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 335, in preorder
    super(SourceWalker, self).preorder(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 105, in preorder
    func(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/customize35.py", line 119, in n_call
    self.default(node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 2016, in default
    self.template_engine(table[key.kind], node)
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/uncompyle6/semantics/pysource.py", line 1981, in template_engine
    remaining = len(node[low:high])
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/collections/__init__.py", line 1096, in __getitem__
    return self.__class__(self.data[i])
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 14, in __init__
    self.kind = intern(kind)
TypeError: intern() argument 1 must be str, not list
```

**Comment by rocky** [comment]
This line
```
  File "/Users/laike9m/.pyenv/versions/3.7.4/lib/python3.7/site-packages/spark_parser/ast.py", line 14, in __init__
```
is saying that the error isn't here but in spark_parser. If you use version 1.8.9 of spark parser released just a little while ago, you should be good for Python 3.7.4 and later Python releases.

**Comment by laike9m** [comment]
That works, thank you.
