### ISSUE TITLE
I get this error please help me!!!

### ISSUE THREAD

**Issue by KANG-NEWBIE** [rocky/python-uncompyle6#287]
```
# uncompyle6 version 3.3.5
# Python bytecode 2.7
# Decompiled from: Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
# Embedded file name: <script>
Traceback (most recent call last):
  File "deshal.py", line 35, in <module>
    Py2()
  File "deshal.py", line 19, in Py2
    xx=decompile(2.7,x,sys.stdout)
  File "C:\Python27\lib\site-packages\uncompyle6\main.py", line 117, in decompile
    is_pypy=is_pypy)
  File "C:\Python27\lib\site-packages\uncompyle6\semantics\pysource.py", line 2339, in code_deparse
    show_asm=debug_opts['asm'])
  File "C:\Python27\lib\site-packages\uncompyle6\scanners\scanner2.py", line 362, in ingest
    j = self.offset2inst_index[offset]
KeyError: 694117
```

**Comment by rocky** [comment]
He KANG-NEWBIE - read and follow the instructions as best as you can when you entered this issue. 

This is the stuff that starts:

```
<!-- __Note:__ Have you read https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md ?

Please remove any of the optional sections if they are not applicable.

Prerequisites

* Make sure the bytecode you have can be disassembled with a
  disassembler.
* Don't put bytecode and corresponding source code on any service that
  requires registration to download.
* When you open a bug report there is no privacy. If the legitimacy of
  the activity is deemed suspicous, I may flag it as suspicious,
  making the issue even more easy to detect.

Bug reports that violate a prerequisite may be discarded.

Note that there are way more bug-fix requestors than there are bug
fixers. If you want you need more immediate, confidential or urgent
assistance

http://www.crazy-compilers.com/decompyle/ offers a byte-code
decompiler service for versions of Python up to 2.6.

-->

## Description

<!-- Add a clear and concise description of the bug. -->

## How to Reproduce
```
