### ISSUE TITLE
Can't decompile this pyo which is python 2.7

### ISSUE THREAD

**Issue by persianpros** [rocky/python-uncompyle6#288]
Would you please check this pyo file: https://github.com/Ednaz/RussianMediaPark/blob/master/RussianMediaPark/plugin.pyo

Here's what I get:

`Traceback (most recent call last):
  File "/usr/local/bin/uncompyle6", line 11, in <module>
    load_entry_point('uncompyle6==3.4.0', 'console_scripts', 'uncompyle6')()
  File "build/bdist.linux-x86_64/egg/uncompyle6/bin/uncompile.py", line 194, in main_bin
  File "build/bdist.linux-x86_64/egg/uncompyle6/main.py", line 261, in main
  File "build/bdist.linux-x86_64/egg/uncompyle6/main.py", line 176, in decompile_file
  File "build/bdist.linux-x86_64/egg/uncompyle6/main.py", line 128, in decompile
  File "build/bdist.linux-x86_64/egg/uncompyle6/semantics/pysource.py", line 2479, in code_deparse
  File "build/bdist.linux-x86_64/egg/uncompyle6/scanners/scanner2.py", line 173, in ingest
  File "build/bdist.linux-x86_64/egg/uncompyle6/scanner.py", line 107, in build_instructions
  File "/usr/local/lib/python2.7/dist-packages/xdis-4.0.3-py2.7.egg/xdis/bytecode.py", line 275, in get_instructions_bytes
    argval, argrepr = _get_const_info(arg, constants)
  File "/usr/local/lib/python2.7/dist-packages/xdis-4.0.3-py2.7.egg/xdis/bytecode.py", line 180, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range`

**Comment by persianpros** [comment]
Still we want to know what's inside this file and we can't decompile it :(
