### ISSUE TITLE
Can't decompile with python 2.7.17

### ISSUE THREAD

**Issue by MarvBob** [rocky/python-uncompyle6#294]
I think it is just the new Python 2.7.17 version that is not registered yet:

```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\uncompyle6.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\uncompyle6\__init__.py", line 48, in <module>
    import uncompyle6.semantics.pysource
  File "c:\python27\lib\site-packages\uncompyle6\semantics\pysource.py", line 136, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "c:\python27\lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "c:\python27\lib\site-packages\uncompyle6\scanners\tok.py", line 163, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "c:\python27\lib\site-packages\uncompyle6\scanners\tok.py", line 59, in __init__
    from xdis.std import _std_api
  File "c:\python27\lib\site-packages\xdis\std.py", line 214, in <module>
    _std_api = make_std_api()
  File "c:\python27\lib\site-packages\xdis\std.py", line 212, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\python27\lib\site-packages\xdis\std.py", line 72, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\python27\lib\site-packages\xdis\op_imports.py", line 156, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '2.7.17'
```

Just in case, more information:
Python 2.7.17 32bits
Windows 10
Not in virtual environment

**Comment by rocky** [comment]
What version of uncompyle6 are you using?  (Hint: if you would have followed the information requested in the template, it suggested you include that.)

**Comment by MarvBob** [comment]
Oh I missed the 3.5.1 release 3 days ago.. Now I feel bad, shame on me.
Sorry for the inconvenience, and thank you.
