### ISSUE TITLE
Calling uncompyle6.main.decompile without the out arg raises AttributeError

### ISSUE THREAD

**Issue by SuperStormer** [rocky/python-uncompyle6#325]
## Description

If you try to call `uncompyle6.main.decompile` with only the bytecode version and the code object, it fails by trying to call `.write()` on None. There should be a default for the `out` arg that doesn't error, given that it is an optional argument.
## How to Reproduce
Call `decompile` with any code object. Sample run below:

```python
>>> from uncompyle6.main import decompile
>>> def a():pass
... 
>>> decompile(None,a.__code__)
# uncompyle6 version 3.7.3
# Python bytecode 3.8
# Decompiled from: Python 3.8.5 (default, Jul 20 2020, 18:32:44) 
# [GCC 9.3.0]
# Embedded file name: <stdin>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/uncompyle6/main.py", line 140, in decompile
    deparsed = deparse_fn(
  File "/home/user/.local/lib/python3.8/site-packages/uncompyle6/semantics/pysource.py", line 2643, in code_deparse
    deparsed.gen_source(deparsed.ast, co.co_name, customize)
  File "/home/user/.local/lib/python3.8/site-packages/uncompyle6/semantics/pysource.py", line 2462, in gen_source
    self.println(self.text)
  File "/home/user/.local/lib/python3.8/site-packages/uncompyle6/semantics/pysource.py", line 472, in println
    self.write(*data)
  File "/home/user/.local/lib/python3.8/site-packages/uncompyle6/semantics/pysource.py", line 468, in write
    self.f.write(out)
AttributeError: 'NoneType' object has no attribute 'write'
```

## Expected behavior

No AttributeError should occur since `out` is an optional argument, meaning leaving it blank should not error.

**Comment by rocky** [comment]
Fixed by cfbb25df
