### ISSUE TITLE
KeyError: '3.8.6' when importing uncompyle6

### ISSUE THREAD

**Issue by MafiaWar** [rocky/python-uncompyle6#330]
Traceback (most recent call last):                                      File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uncompyle6/__init__.py", line 53, in <module>                               import uncompyle6.semantics.pysource
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uncompyle6/semantics/pysource.py", line 141, in <module>                    from uncompyle6.parsers.treenode import SyntaxTree
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uncompyle6/parsers/treenode.py", line 3, in <module>                        from uncompyle6.scanners.tok import NoneToken
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uncompyle6/scanners/tok.py", line 200, in <module>                          NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uncompyle6/scanners/tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/xdis/op_imports.py", line 169, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.6'

**Comment by finackninja** [comment]
Same issue for me on Kali Linux 2020.3:

`kali@kali:~/Downloads$ sudo pip3 install uncompyle6-3.7.4-py3-none-any.whl 
Processing ./uncompyle6-3.7.4-py3-none-any.whl
Collecting xdis<5.1.0,>=5.0.4
  Using cached xdis-5.0.4-py38-none-any.whl (126 kB)
Requirement already satisfied: spark-parser<1.9.0,>=1.8.9 in /usr/local/lib/python3.8/dist-packages (from uncompyle6==3.7.4) (1.8.9)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from spark-parser<1.9.0,>=1.8.9->uncompyle6==3.7.4) (7.1.2)
Installing collected packages: xdis, uncompyle6
  Attempting uninstall: xdis
    Found existing installation: xdis 4.5.1
    Uninstalling xdis-4.5.1:
      Successfully uninstalled xdis-4.5.1
Successfully installed uncompyle6-3.7.4 xdis-5.0.4
kali@kali:~/Downloads$ uncompyle6 --version
Traceback (most recent call last):
  File "/usr/local/bin/uncompyle6", line 5, in <module>
    from uncompyle6.bin.uncompile import main_bin
  File "/usr/local/lib/python3.8/dist-packages/uncompyle6/__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "/usr/local/lib/python3.8/dist-packages/uncompyle6/semantics/pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "/usr/local/lib/python3.8/dist-packages/uncompyle6/parsers/treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "/usr/local/lib/python3.8/dist-packages/uncompyle6/scanners/tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "/usr/local/lib/python3.8/dist-packages/uncompyle6/scanners/tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "/usr/local/lib/python3.8/dist-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/usr/local/lib/python3.8/dist-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/usr/local/lib/python3.8/dist-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/usr/local/lib/python3.8/dist-packages/xdis/op_imports.py", line 169, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.6'
kali@kali:~/Downloads$ python3 --version
Python 3.8.6
kali@kali:~/Downloads$ python --version
Python 2.7.18
kali@kali:~/Downloads$ cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.3"
VERSION_ID="2020.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
`

**Comment by MafiaWar** [comment]
I use termux

**Comment by rocky** [comment]
This stuff is handled by xids. The version of xdis in git understands 3.8.6

**Comment by camabeh** [comment]
Why is it closed? I've just tried master branch and it still doesnt work.
