### ISSUE TITLE
KeyError: '3.9.1' when importing uncompyle6 

### ISSUE THREAD

**Issue by dz-id** [rocky/python-uncompyle6#338]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/uncompyle6", line 5, in <module>
    from uncompyle6.bin.uncompile import main_bin
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/semantics/pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/parsers/treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/scanners/tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/uncompyle6/scanners/tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/xdis/std.py", line 220, in <module>
    _std_api = make_std_api()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/xdis/std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/xdis/std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/xdis/op_imports.py", line 170, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.9.1'

**Comment by rocky** [comment]
The key error indicates that xdis needs to learn that there's now a 3.9.1

But if that were fixed uncompyle6 would still fail since 3.9.x isn't being worked on.
