### ISSUE TITLE
KeyError: '3.8.7candidate1'

### ISSUE THREAD

**Issue by harith75** [rocky/python-uncompyle6#359]
Hello sir l do lhave this problem while trying to decompyle  : 
PS D:\Users\user\OneDrive - LISI\Bureau\python-decompile3-master> decompyle3 EXE_newProtocol_I2C_V6.pyc
Traceback (most recent call last):
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\decompyle3-script.py", line 33, in <module>
    sys.exit(load_entry_point('decompyle3==3.7.6', 'console_scripts', 'decompyle3')())
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\Scripts\decompyle3-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\__init__.py", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\semantics\pysource.py", line 139, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\parsers\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\parsers\treenode.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\scanners\tok.py", line 201, in <module>
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\decompyle3-3.7.6-py3.8.egg\decompyle3\scanners\tok.py", line 83, in __init__
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\xdis-5.0.12-py3.8.egg\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\xdis-5.0.12-py3.8.egg\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\xdis-5.0.12-py3.8.egg\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "D:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\xdis-5.0.12-py3.8.egg\xdis\op_imports.py", line 173, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.8.7candidate1'

**Comment by harith75** [comment]
By the way l'm using python 3.8..7 
Thanks

**Comment by rocky** [comment]
We don't support release candidates. This is noted in in bold in https://github.com/rocky/python-uncompyle6/blob/master/README.rst. I have also just added it to https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md.
