### ISSUE TITLE
[WinError 5] Access is denied on Python 3.10

### ISSUE THREAD

**Issue by Slimakoi** [rocky/python-uncompyle6#368]
## Description

When trying to decompile a python file in python 3.10.0 in decompyle6 it raises a `PermissionError` exception. I'm on windows 11 (build 22504.1010)

## How to Reproduce

```console
C:\Users\Slimakoi\Desktop\Coding\encryption>uncompyle6 sample-berserker.py
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\uncompyle6-script.py", line 33, in <module>
    sys.exit(load_entry_point('uncompyle6==3.8.1.dev0', 'console_scripts', 'uncompyle6')())
  File "C:\Program Files\Python310\lib\site-packages\uncompyle6-3.8.1.dev0-py3.10.egg\uncompyle6\bin\uncompile.py", line 196, in main_bin
  File "C:\Program Files\Python310\lib\site-packages\uncompyle6-3.8.1.dev0-py3.10.egg\uncompyle6\main.py", line 304, in main
  File "C:\Program Files\Python310\lib\site-packages\uncompyle6-3.8.1.dev0-py3.10.egg\uncompyle6\main.py", line 174, in decompile_file
  File "C:\Program Files\Python310\lib\site-packages\xdis-6.0.3-py3.10.egg\xdis\load.py", line 84, in check_object_path
    py_compile.compile(spath, cfile=path, doraise=True)
  File "C:\Program Files\Python310\lib\py_compile.py", line 172, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 198, in _write_atomic
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Slimakoi\\AppData\\Local\\Temp\\sample-berserker-6v0a5fm5.pyc.2128985858480' -> 'C:\\Users\\Slimakoi\\AppData\\Local\\Temp\\sample-berserker-6v0a5fm5.pyc'
```

## Expected behavior

I never used decompyler6 before so I don't know what the outcome should be but it's definetly not this

## Environment

- uncompyle6 --version
```
uncompyle6 3.8.1.dev0
```

- pip show uncompyle6
```
Name: uncompyle6
Version: 3.8.1.dev0
Summary: Python cross-version byte-code decompiler
Home-page: https://github.com/rocky/python-uncompyle6/
Author: Rocky Bernstein, Hartmut Goebel, John Aycock, and others
Author-email: rb@dustyfeet.com
License: GPL3
Location: c:\program files\python310\lib\site-packages\uncompyle6-3.8.1.dev0-py3.10.egg
Requires: spark-parser, xdis
Required-by:
```

- python -c "import sys; print(sys.version)"
```
3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
```

## Additional Environment or Context

I have python added to PATH

**Comment by rocky** [comment]
Looks like no one is willing to help you. :-(
