### ISSUE TITLE
co_code should be one of the types

### ISSUE THREAD

**Issue by Noietch** [rocky/python-uncompyle6#392]
Unknown type 64 @
Unknown type 0
Unknown type 0
Unknown type 0
Unknown type 0
Traceback (most recent call last):
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\load.py", line 304, in load_module_from_file_object
    co = xdis.unmarshal.load_code(fp, magic_int, code_objects)
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\unmarshal.py", line 565, in load_code
    return um_gen.load()
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\unmarshal.py", line 179, in load
    return self.r_object()
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\unmarshal.py", line 222, in r_object
    return unmarshal_func(save_ref, bytes_for_s)
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\unmarshal.py", line 520, in t_code
    code = to_portable(
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\codetype\__init__.py", line 200, in to_portable
    return codeType2Portable(code, version_triple)
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\codetype\__init__.py", line 43, in codeType2Portable
    return Code3(
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\codetype\code30.py", line 80, in __init__
    self.check()
  File "c:\users\cary\appdata\local\programs\python\python38\lib\site-packages\xdis\codetype\code13.py", line 87, in check
    assert type(val) in fieldtype, "%s should be one of the types %s; is type %s" % (field, fieldtype, type(val))
AssertionError: co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>
Ill-formed bytecode file black-box.pyc
<class 'AssertionError'>; co_code should be one of the types (<class 'str'>, <class 'bytes'>, <class 'list'>, <class 'tuple'>); is type <class 'NoneType'>

**Comment by Luwill6** [comment]
How to fix this bug?

**Comment by rocky** [comment]
The bug is may be in not reading [instructions](https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md). So let me turn that around: you tell me how to fix this?
