### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by tahaghafuri** [rocky/python-uncompyle6#425]
i'm error on running the uncompyle6:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Scripts\uncompyle6.exe\__main__.py", line 4, in <module>
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\uncompyle6\__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\uncompyle6\semantics\pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\uncompyle6\scanners\tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\uncompyle6\scanners\tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
               ^^^^^^^^^^^^^^
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Taha Amin Ghafuri\scoop\apps\python\current\Lib\site-packages\xdis\op_imports.py", line 174, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '3.11.1'

**Comment by rocky** [comment]
3.11 is not supported.
