### ISSUE TITLE
Unicodeerror for u266f in Python 3.7 file

### ISSUE THREAD

**Issue by markusschloesser** [rocky/python-uncompyle6#456]
Hi,
## Description.
I have a file (Midi Remote Script for Ableton, OK to decompile), which has the char u266f (which the musical sign for sharp #). 
Uncompyle6 will fail for that file with a unicodeerror:

## How to Reproduce

```
import os
import uncompyle6
your_directory = r'M:\Music Software\mackie c4 pro c4c_pc_v1.0\Live 11.3\11.3.1b5\ableton\v3\base'
for dirpath, b, filenames in os.walk(your_directory):
    for filename in filenames:
        if not filename.endswith('.pyc'):
            continue

        filepath = dirpath + '/' + filename
        original_filename = filename.split('.')[0]
        original_filepath = dirpath + '/' + original_filename + '.py'
        with open(original_filepath, 'w') as f:
            uncompyle6.decompile_file(filepath, f)
```

Python bytecode attached:
[util.zip](https://github.com/rocky/python-uncompyle6/files/11537454/util.zip)

-->

## Output Given

```
Traceback (most recent call last):
  File "C:\Users\Markus\PycharmProjects\C4P3\z_utility\tools MS\decompyle3 test.py", line 13, in <module>
    decompyle3.decompile_file(filepath, f)
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\main.py", line 231, in decompile_file
    decompile(
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\main.py", line 158, in decompile
    deparsed = deparse_fn(
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\semantics\pysource.py", line 1181, in code_deparse
    deparsed.gen_source(
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\semantics\pysource.py", line 986, in gen_source
    printfn(self.text)
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\semantics\pysource.py", line 482, in println
    self.write(*data)
  File "C:\Users\Markus\AppData\Roaming\Python\Python310\site-packages\decompyle3\semantics\pysource.py", line 478, in write
    self.f.write(out)
  File "C:\Users\Markus\AppData\Local\Programs\Thonny\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u266f' in position 696: character maps to <undefined>
```

## Expected behavior

Not fail over the sharp sign

## Environment

Win10 , Thonny, uncomyple6 version 3.9, other files work fine

**Comment by markusschloesser** [comment]
Thanks!
I checked and my xdis is v 6.0.5.
Also have another file with the same error 
[physical_display.zip](https://github.com/rocky/python-uncompyle6/files/11556990/physical_display.zip)
So any idea, why this fails on my Windows machine?

**Comment by rocky** [comment]
Are you using what is in git or what was released? You need to use what is in git.

**Comment by markusschloesser** [comment]
that worked, thank you!

Are you interested in further issues? (Unfortunately I cannot contribute with code)

**Comment by rocky** [comment]
> that worked, thank you!
> 
> Are you interested in further issues? (Unfortunately I cannot contribute with code)

Everyone is free to report bugs. The ones that show effort to narrow the problem down and are thoughtful - follow the information given in posting a bug report or reflect that https://github.com/rocky/python-uncompyle6/blob/master/HOW-TO-REPORT-A-BUG.md has been read and followed  - are the one that are more likely to get fixed sooner. 

But let me answer your question with one of my own: Are you interested in funding the project? See also [this](https://github.com/Mathics3/mathics-core/discussions/860#discussioncomment-6030695) where I talk about the frequent comment: "Unfortunately I cannot contribute with code".
