### ISSUE TITLE
KeyError: '3.11.4'

### ISSUE THREAD

**Issue by fuckzeroo** [rocky/python-uncompyle6#464]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Scripts\uncompyle6.exe\__main__.py", line 4, in <module>
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\semantics\pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\scanners\tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\scanners\tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
               ^^^^^^^^^^^^^^
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Menot\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\op_imports.py", line 174, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '3.11.4'
```

**Comment by vz00000** [comment]
how can i fix that i tried updating xdis to the latest version but still having the same problem

**Comment by bloban** [comment]
Did you fix it?

**Comment by sibelsimsek** [comment]
Did you fix it?

**Comment by oygenvalue** [comment]
Im having the same issue...

**Comment by xplo1t-sec** [comment]
I am on Python 3.11.2 and I also have this issue. Anyone got any fixes or workarounds for this one?

**Comment by SirKnightV** [comment]
i had same problem i solve it downgrading my python 3.11.5 to 3.10.0

**Comment by xunoaib** [comment]
For future bug reports (on any project), please remember to include relevant **version numbers** of the packages you're using as well as the command(s) being run. You have an old version of `xdis` and/or `uncompyle6`, presumably installed via PyPI. Check your version numbers (`pip list`) and consider installing those packages from git, as the PyPI versions seem out of date:

```
pip install git+https://github.com/rocky/python-xdis
pip install git+https://github.com/rocky/python-uncompyle6
```

[xdis does support Python versions through 3.11.5](https://github.com/rocky/python-xdis/blob/5d27aba1ce68f244ed701de52792759d671ed66b/xdis/magics.py#L503) and I've had success with it.
