### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DevSimpler** [rocky/python-uncompyle6#473]
~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '3.11.5'
PS C:\Users\clou1\OneDrive\Desktop\projects\deez nuts> python3 main.py main.pyc
C:\Users\clou1\OneDrive\Desktop\projects\deez nuts\main.py:34: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses 
  import imp
Traceback (most recent call last):
  File "C:\Users\clou1\OneDrive\Desktop\projects\deez nuts\main.py", line 49, in <module>
    SETUP_LOOP, BREAK_LOOP, CONTINUE_LOOP,
    ^^^^^^^^^^
NameError: name 'SETUP_LOOP' is not defined
PS C:\Users\clou1\OneDrive\Desktop\projects\deez nuts> uncompyle6 --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Scripts\uncompyle6.exe\__main__.py", line 4, in <module>
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\semantics\pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\scanners\tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\uncompyle6\scanners\tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
               ^^^^^^^^^^^^^^
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\clou1\AppData\Local\Programs\Python\Python311\Lib\site-packages\xdis\op_imports.py", line 174, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
                      ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: '3.11.5'

**Comment by rocky** [comment]
#460
