### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by xtyy0510** [rocky/python-uncompyle6#494]
Unknown type 0 (hex 0)
Traceback (most recent call last):
  File "D:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python38\Scripts\uncompyle6.exe\__main__.py", line 7, in <module>
  File "D:\Python38\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python38\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Python38\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python38\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python38\lib\site-packages\uncompyle6\bin\uncompile.py", line 225, in main_bin
    result = main(
  File "D:\Python38\lib\site-packages\uncompyle6\main.py", line 340, in main
    deparsed_objects = decompile_file(
  File "D:\Python38\lib\site-packages\uncompyle6\main.py", line 243, in decompile_file
    decompile(
  File "D:\Python38\lib\site-packages\uncompyle6\main.py", line 104, in decompile
    assert iscode(co), f"""{co} does not smell like code"""
AssertionError: None does not smell like code

**Comment by rocky** [comment]
Please read and follow instructions.
