### ISSUE TITLE
Decompilation failed with if-else ternary operator embedded into a boolean expression

### ISSUE THREAD

**Issue by davidedb** [rocky/python-uncompyle6#5]
Hello,

thanks for making your tool freely available: this is exactly what I was looking for!
Unfortunately I'm encountering a little problem.
I've just cloned the source repository and tested uncompyle6 with one of my libraries.
The decompilation failed with the following error code:

> Syntax error at or near `RETURN_END_IF' token at offset 21

I succeeded in restricting the failing code to the one generated by the following function:

```
def minimum(x, y):
    return x or (x if x < y else y)
```
The same error is generated if I replace the bolloean operator `or` with `and`.

Below is the whole transcript of my little session:

```
python -c 'import testcase' && uncompyle6 testcase.pyc
# Python 2.7 (decompiled from Python 2.7)
# Embedded file name: testcase.py
# Compiled at: 2016-04-04 17:47:25


def minimum--- This code section failed: ---

   2       0	LOAD_FAST         'x'
           3	JUMP_IF_FALSE_OR_POP '25'
           6	LOAD_FAST         'x'
           9	LOAD_FAST         'y'
          12	COMPARE_OP        '<'
          15	POP_JUMP_IF_FALSE '22'
          18	LOAD_FAST         'x'
          21	RETURN_END_IF     ''
          22	LOAD_FAST         'y'
        25_0	COME_FROM         '3'
          25	RETURN_VALUE      ''
          -1	RETURN_LAST       ''


# Deparsing stopped due to parse error
# Can't uncompile testcase.pyc
Syntax error at or near `RETURN_END_IF' token at offset 21                                     
```

This seems the same issue described in [Conditional lambda problems](https://github.com/wibiti/uncompyle2/issues/21)

**Comment by rocky** [comment]
I looked at a little and there is weird stuff going on. I generally am too tired at night to devote the proper attention it needs. unpycdc uncompiles as: 

```
def minimum(x, y):
    if not x:
        if x < y:
            return x
```
which I think is wrong.

**Comment by davidedb** [comment]
In case it could help, I noticed that the current uncompyle2 version decompiles my testcase correctly.

**Comment by rocky** [comment]
Thanks. I think this will help.

**Comment by rocky** [comment]
Hmmm. I don't think uncompyle2 is correct in its deparsing either. It gives: 

```python
def minimum(x, y):
    if x < y:
        return x
    return y
```

This differs when _x_ is non-zero. In that case _x_ is returned whether or ot it is less than y.

**Comment by davidedb** [comment]
Hi, rocky,

I've used the current development version of uncompyle2 and it works correctly.
Here is my little `testcase.py`:
```
def minimum(x, y):
    return x if x < y else y

def test1(x, y):
    return x or (x if x < y else y)

def test2(x, y):
    return x and (x if x < y else y)
```
And this is the output I get running the test command `python -c 'import testcase' && uncompyle2 testcase.pyc`:
```
# 2016.04.05 13:05:59 CEST
#Embedded file name: testcase.py

def minimum(x, y):
    if x < y:
        return x
    return y

def test1(x, y):
    return x or (x if x < y else y)

def test2(x, y):
    return x and (x if x < y else y)

+++ okay decompyling testcase.pyc 56
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2016.04.05 13:05:59 CEST
```

It seems fine to me.

**Comment by davidedb** [comment]
The previous trivial testcase generates 2 errors in uncompyle6:
```
# Python 2.7 (decompiled from Python 2.7)
# Embedded file name: testcase.py
# Compiled at: 2016-04-05 12:07:12

def minimum(x, y):
    if x < y:
        return x
    return y

def test1--- This code section failed: ---

   7       0	LOAD_FAST         'x'
           3	JUMP_IF_TRUE_OR_POP '25'
           6	LOAD_FAST         'x'
           9	LOAD_FAST         'y'
          12	COMPARE_OP        '<'
          15	POP_JUMP_IF_FALSE '22'
          18	LOAD_FAST         'x'
          21	RETURN_END_IF     ''
          22	LOAD_FAST         'y'
        25_0	COME_FROM         '3'
          25	RETURN_VALUE      ''
          -1	RETURN_LAST       ''

Syntax error at or near `RETURN_END_IF' token at offset 21

def test2--- This code section failed: ---

  11       0	LOAD_FAST         'x'
           3	JUMP_IF_FALSE_OR_POP '25'
           6	LOAD_FAST         'x'
           9	LOAD_FAST         'y'
          12	COMPARE_OP        '<'
          15	POP_JUMP_IF_FALSE '22'
          18	LOAD_FAST         'x'
          21	RETURN_END_IF     ''
          22	LOAD_FAST         'y'
        25_0	COME_FROM         '3'
          25	RETURN_VALUE      ''
          -1	RETURN_LAST       ''

# Deparsing stopped due to parse error
# Can't uncompile testcase.pyc
Syntax error at or near `RETURN_END_IF' token at offset 21
```

**Comment by rocky** [comment]
Ok. Where can I find "the current development version of uncompyle2" ? URL or tarball of sourcecode please.

**Comment by davidedb** [comment]
The code is hosted on github at [https://github.com/wibiti/uncompyle2](https://github.com/wibiti/uncompyle2).
I got it using the command `git clone https://github.com/wibiti/uncompyle2.git.`

**Comment by rocky** [comment]
I'm still getting the same error as I get in uncompyle6. Try adding the `-a` and `-t` options to show the abstract syntax tree as well as the assembly. And post that here. Thanks.

```
$ python -c 'import testcase'
$ uncompyle2 ./testcase.pyc
# 2016.04.05 21:00:56 EDT
# Embedded file name: testcase.py


def minimum(x, y):
    if x < y:
        return x
    return y


def test1--- This code section failed: ---

0	LOAD_FAST         'x'
3	JUMP_IF_TRUE_OR_POP '25'
6	LOAD_FAST         'x'
9	LOAD_FAST         'y'
12	COMPARE_OP        '<'
15	POP_JUMP_IF_FALSE '22'
18	LOAD_FAST         'x'
21	RETURN_END_IF     None
22	LOAD_FAST         'y'
25_0	COME_FROM         '3'
25	RETURN_VALUE      None
-1	RETURN_LAST       None

Syntax error at or near `RETURN_END_IF' token at offset 21


def test2--- This code section failed: ---

0	LOAD_FAST         'x'
3	JUMP_IF_FALSE_OR_POP '25'
6	LOAD_FAST         'x'
9	LOAD_FAST         'y'
12	COMPARE_OP        '<'
15	POP_JUMP_IF_FALSE '22'
18	LOAD_FAST         'x'
21	RETURN_END_IF     None
22	LOAD_FAST         'y'
25_0	COME_FROM         '3'
25	RETURN_VALUE      None
-1	RETURN_LAST       None


# Can't uncompyle ./testcase.pyc
Traceback (most recent call last):
  File "/home/rocky/.pyenv/versions/2.7.10/lib/python2.7/site-packages/uncompyle2/__init__.py", line 203, in main
    uncompyle_file(infile, outstream, showasm, showast)
  File "/home/rocky/.pyenv/versions/2.7.10/lib/python2.7/site-packages/uncompyle2/__init__.py", line 140, in uncompyle_file
    uncompyle(version, co, outstream, showasm, showast)
  File "/home/rocky/.pyenv/versions/2.7.10/lib/python2.7/site-packages/uncompyle2/__init__.py", line 129, in uncompyle
    raise walk.ERROR
ParserError: --- This code section failed: ---

0	LOAD_FAST         'x'
3	JUMP_IF_FALSE_OR_POP '25'
6	LOAD_FAST         'x'
9	LOAD_FAST         'y'
12	COMPARE_OP        '<'
15	POP_JUMP_IF_FALSE '22'
18	LOAD_FAST         'x'
21	RETURN_END_IF     None
22	LOAD_FAST         'y'
25_0	COME_FROM         '3'
25	RETURN_VALUE      None
-1	RETURN_LAST       None

Syntax error at or near `RETURN_END_IF' token at offset 21

Syntax error at or near `RETURN_END_IF' token at offset 21# decompiled 0 files: 0 okay, 1 failed, 0 verify failed
# 2016.04.05 21:00:56 EDT
$ grep url ./.git/config
	url = https://github.com/Mysterie/uncompyle2.git
$ ```

**Comment by rocky** [comment]
I also note that if I deparse Python 2.6 bytecode I don't have a problem.

**Comment by davidedb** [comment]
Sorry, rocky,
I was out of my office yesterday and tried to recall the source of the uncompyle2 version I used for my testing by using my phone: unfortunately I failed and told you a wrong source.

I installed uncompyle2 simply by running `pip install uncompyle2`.

Sorry for any inconvenience.
--Davide

**Comment by davidedb** [comment]
Below is the output of uncompyle2 with the options you suggested:

```
1733 $ uncompyle2 -a -t testcase.pyc
# 2016.04.06 10:51:32 CEST
#Embedded file name: testcase.py

0	LOAD_CONST        '<code_object minimum>'
3	MAKE_FUNCTION_0   None
6	STORE_NAME        'minimum'

9	LOAD_CONST        '<code_object test1>'
12	MAKE_FUNCTION_0   None
15	STORE_NAME        'test1'

18	LOAD_CONST        '<code_object test2>'
21	MAKE_FUNCTION_0   None
24	STORE_NAME        'test2'
27	LOAD_CONST        None
30	RETURN_VALUE      None

stmts
sstmt
   stmt
      funcdef
         mkfunc
            
               0	LOAD_CONST        '<code_object minimum>'
            3	MAKE_FUNCTION_0   None
         designator
            6	STORE_NAME        'minimum'
sstmt
   stmt
      funcdef
         mkfunc
            
               9	LOAD_CONST        '<code_object test1>'
            12	MAKE_FUNCTION_0   None
         designator
            15	STORE_NAME        'test1'
sstmt
   stmt
      funcdef
         mkfunc
            
               18	LOAD_CONST        '<code_object test2>'
            21	MAKE_FUNCTION_0   None
         designator
            24	STORE_NAME        'test2'
0	LOAD_FAST         'x'
3	LOAD_FAST         'y'
6	COMPARE_OP        '<'
9	POP_JUMP_IF_FALSE '16'
12	LOAD_FAST         'x'
15	RETURN_END_IF     None
16	LOAD_FAST         'y'
19	RETURN_VALUE      None


0	LOAD_FAST         'x'
3	JUMP_IF_TRUE_OR_POP '25'
6	LOAD_FAST         'x'
9	LOAD_FAST         'y'
12	COMPARE_OP        '<'
15	POP_JUMP_IF_FALSE '22'
18	LOAD_FAST         'x'
21	RETURN_END_IF     None
22	LOAD_FAST         'y'
25_0	COME_FROM         '3'
25	RETURN_VALUE      None


0	LOAD_FAST         'x'
3	JUMP_IF_FALSE_OR_POP '25'
6	LOAD_FAST         'x'
9	LOAD_FAST         'y'
12	COMPARE_OP        '<'
15	POP_JUMP_IF_FALSE '22'
18	LOAD_FAST         'x'
21	RETURN_END_IF     None
22	LOAD_FAST         'y'
25_0	COME_FROM         '3'
25	RETURN_VALUE      None



def minimumstmts
sstmt
   stmt
      ifstmt
         testexpr
            testfalse
               expr
                  cmp
                     compare
                        expr
                           
                              0	LOAD_FAST         'x'
                        expr
                           3	LOAD_FAST         'y'
                        6	COMPARE_OP        '<'
               jmp_false
                  9	POP_JUMP_IF_FALSE '16'
         _ifstmts_jump
            return_if_stmts
               return_if_stmt
                  ret_expr
                     expr
                        12	LOAD_FAST         'x'
                  15	RETURN_END_IF     None
sstmt
   return_stmt
      ret_expr
         expr
            16	LOAD_FAST         'y'
      19	RETURN_VALUE      None
   -1	RETURN_LAST       None
(x, y):
    if x < y:
        return x
    return y


def test1stmts
sstmt
   return_stmt
      ret_expr
         ret_or
            expr
               
                  0	LOAD_FAST         'x'
            3	JUMP_IF_TRUE_OR_POP '25'
            ret_expr_or_cond
               ret_cond
                  expr
                     cmp
                        compare
                           expr
                              6	LOAD_FAST         'x'
                           expr
                              9	LOAD_FAST         'y'
                           12	COMPARE_OP        '<'
                  15	POP_JUMP_IF_FALSE '22'
                  expr
                     18	LOAD_FAST         'x'
                  21	RETURN_END_IF     None
                  ret_expr_or_cond
                     ret_expr
                        expr
                           22	LOAD_FAST         'y'
            25_0	COME_FROM         '3'
      25	RETURN_VALUE      None
   -1	RETURN_LAST       None
(x, y):
    return x or (x if x < y else y)


def test2stmts
sstmt
   return_stmt
      ret_expr
         ret_and
            expr
               
                  0	LOAD_FAST         'x'
            3	JUMP_IF_FALSE_OR_POP '25'
            ret_expr_or_cond
               ret_cond
                  expr
                     cmp
                        compare
                           expr
                              6	LOAD_FAST         'x'
                           expr
                              9	LOAD_FAST         'y'
                           12	COMPARE_OP        '<'
                  15	POP_JUMP_IF_FALSE '22'
                  expr
                     18	LOAD_FAST         'x'
                  21	RETURN_END_IF     None
                  ret_expr_or_cond
                     ret_expr
                        expr
                           22	LOAD_FAST         'y'
            25_0	COME_FROM         '3'
      25	RETURN_VALUE      None
   -1	RETURN_LAST       None
(x, y):
    return x and (x if x < y else y)
+++ okay decompyling testcase.pyc 56
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2016.04.06 10:51:32 CEST

```

**Comment by rocky** [comment]
I think commit 9f7d36f addresses this problem. If so, close the issue. 

I'm not sure I would have been able to come up with the grammar change as quickly (if at all since I'm very busy), if I didn't have that particular source code to consult. So thanks for that. 

Somebody at some point must've worked on this. But due to the sad nature of the various branches of the code that are out there, some of them not being in a public version control, that effort might have been lost in history if you hadn't pointed it out.

**Comment by davidedb** [comment]
Thanks, rocky!
It works perfectly both with the testcase and with my full library.

Thanks again for your prompt support!
--Davide
