### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Warriorak1** [rocky/python-uncompyle6#77]
When I do this command on any file, for example this command:
C:\Users\UnknownWarrior8910\Desktop\uncomp>`uncompyle6 modloader.pyc > un.txt`
This happens:
`Traceback (most recent call last):
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\Scripts\uncompyle6-script.py", line 11, in <module>
    load_entry_point('uncompyle6==2.9.9', 'console_scripts', 'uncompyle6')()
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\bin\uncompile.py", line 163, in main_bin
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\main.py", line 145, in main
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\main.py", line 72, in uncompyle_file
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\main.py", line 46, in uncompyle
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\semantics\pysource.py", line 2256, in deparse_code
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\scanners\scanner2.py", line 135, in ingest
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\scanners\scanner2.py", line 971, in find_jump_targets
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\scanners\scanner2.py", line 635, in detect_control_flow
  File "C:\Users\UnknownWarrior8910\AppData\Local\Programs\Python\Python36-32\lib\site-packages\uncompyle6-2.9.9-py3.6.egg\uncompyle6\scanners\scanner2.py", line 474, in next_except_jump
AssertionError`

What should I do with this?
Im using it on windows 10.

**Comment by rocky** [comment]
Probably the simplest thing to do is to attach `modloader.pyc`. 

A guess is that if you were to disassemble the file, it wouldn't be valid bytecode.
