### ISSUE TITLE
Parse error at or near `POP_BLOCK'

### ISSUE THREAD

**Issue by comet0** [rocky/python-uncompyle6#82]
```
$ python2 -m compyleall test.py
Compiling test.py ...

$ python3 -c "import uncompyle6, sys;uncompyle6.uncompyle_file('test.pyc', sys.stdout)"
# uncompyle6 version 2.9.9
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
# [GCC 5.4.0 20160609]
# Embedded file name: test.py
# Compiled at: 2017-01-27 16:38:32
Instruction context:
   
  11      43  JUMP_BACK             3  'to 3'
             46  JUMP_BACK             3  'to 3'
->           49  POP_BLOCK        


def test--- This code section failed: ---

   3       0  SETUP_LOOP           47  'to 50'
           3  LOAD_GLOBAL           0  'True'
           6  POP_JUMP_IF_FALSE    49  'to 49'

   4       9  LOAD_CONST            1  1
          12  STORE_FAST            1  'x'

   5      15  LOAD_FAST             1  'x'
          18  POP_JUMP_IF_FALSE    37  'to 37'

   6      21  LOAD_FAST             1  'x'
          24  POP_JUMP_IF_FALSE     3  'to 3'

   7      27  BREAK_LOOP       
          28  JUMP_ABSOLUTE        46  'to 46'

   9      31  JUMP_BACK             3  'to 3'
          34  JUMP_BACK             3  'to 3'

  10      37  LOAD_FAST             1  'x'
          40  POP_JUMP_IF_FALSE     3  'to 3'

  11      43  JUMP_BACK             3  'to 3'
          46  JUMP_BACK             3  'to 3'
          49  POP_BLOCK        
        50_0  COME_FROM                '0'

Parse error at or near `POP_BLOCK' instruction at offset 49Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6-2.9.9-py3.5.egg/uncompyle6/main.py", line 46, in uncompyle
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6-2.9.9-py3.5.egg/uncompyle6/semantics/pysource.py", line 2302, in deparse_code
uncompyle6.semantics.pysource.SourceWalkerError: Deparsing stopped due to parse error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6-2.9.9-py3.5.egg/uncompyle6/main.py", line 72, in uncompyle_file
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6-2.9.9-py3.5.egg/uncompyle6/main.py", line 49, in uncompyle
uncompyle6.semantics.pysource.SourceWalkerError: Deparsing stopped due to parse error
```
```
$ cat test.py
def test(self):
    while True:
        x = 1
        if x:
            if x:
                break
            else:
                continue
        elif x:
            pass
```

If test.py is compiled with Python3 decompilation is successful
Python2 version is ```Python 2.7.12```

**Comment by comet0** [comment]
Sorry, just pulled fresh from git and the problem is solved, closing issue.

**Comment by rocky** [comment]
Just so you know. Yes, there are still a number of control-flow problems in uncompyle6. It is one of the things I am working on when I have free time which is recently not a lot of time.

But as unsolid uncompyle6 is with control flow that's also the case in every other Python decompiler I have seen. 

What's really needed is a total reworking of how uncompyle6 turns control flow into python compound statements (if, while, for, try, with) That will take a bit of time though.
